"""A read-only evidence dashboard; all displayed values come from the published mart."""
from html import escape


def render(summary):
    def table(rows, columns):
        if not rows: return '<p>No observations known at this cutoff.</p>'
        return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+escape(label)+'</th>' for _,label in columns)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+escape('Unknown' if row.get(key) is None else str(row[key]))+'</td>' for key,_ in columns)+'</tr>' for row in rows)+'</tbody></table></div>'
    weeks=summary.get('weeks',[]); days=summary.get('days',[])
    sessions=sum(row['sessions'] for row in weeks)
    duration=sum(row['duration_seconds'] for row in weeks)/60
    fresh=all(item['fresh'] for item in summary.get('freshness',{}).values()) and bool(summary.get('freshness'))
    return '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fitness / Data confidence</title><style>
    *{box-sizing:border-box}body{margin:0;background:#101d25;color:#eaf1f3;font:16px system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:48px 28px}.brand{letter-spacing:.15em;color:#8ed9b4;font-size:13px}h1{font-size:clamp(32px,5vw,60px);line-height:1.08;margin:24px 0 16px;font-weight:600}p{color:#b5c5ce;line-height:1.6;max-width:740px}.metrics{display:flex;gap:48px;border-block:1px solid #37505a;padding:28px 0;margin:36px 0;flex-wrap:wrap}.metric strong{display:block;font-size:36px;color:#8ed9b4}.metric span{color:#b5c5ce}h2{margin-top:38px;font-size:23px}table{width:100%;border-collapse:collapse;font-size:14px;text-align:left}td,th{padding:15px 12px;border-bottom:1px solid #37505a}th{color:#8ed9b4;font-weight:500}.scroll{overflow:auto}footer{border-top:1px solid #37505a;margin-top:40px;padding-top:24px;color:#b5c5ce;font-size:13px}.tag{display:inline-block;padding:6px 10px;border:1px solid #8ed9b4;border-radius:4px;color:#8ed9b4}</style><main>
    <div class="brand">FITNESS DATA PLATFORM / V1</div><h1>Your activity.<br>With the evidence intact.</h1><p>Point-in-time summaries from validated exports. Device identity, corrections and late arrivals stay traceable. Missing observations stay unknown.</p><span class="tag">Synthetic demonstration data</span>
    '''+f'<div class="metrics"><div class="metric"><strong>{sessions}</strong><span>Canonical workouts</span></div><div class="metric"><strong>{duration:g}</strong><span>Observed minutes</span></div><div class="metric"><strong>{"Fresh" if fresh else "Check sources"}</strong><span>At published cutoff</span></div></div><p>Knowledge cutoff: {escape(summary.get("as_of","Unknown"))}. This is a historical snapshot, not a claim that the sources are fresh now.</p>'+'<h2>Weekly activity</h2>'+table(weeks,[('week_start','Week starting'),('activity','Activity'),('sessions','Workouts'),('observed_days','Observed days'),('duration_seconds','Seconds'),('distance_m','Metres'),('distance_observed_sessions','Distance coverage')])+'<h2>Daily observations</h2>'+table(days,[('local_date','Local date'),('activity','Activity'),('sessions','Workouts'),('duration_seconds','Seconds'),('distance_m','Metres')])+'''<footer>Whole workouts belong to their local start day. Distances count only measured sessions; days without exports are unknown. This project demonstrates data engineering and does not provide medical advice or evaluate health outcomes.</footer></main></html>'''
